# These are supported funding model platforms
# Uncomment and fill in the ones you use. Delete this file if you do not want a Sponsor button.

github: [prathamshukla28]
# patreon: your-username
# open_collective: your-collective
# ko_fi: your-username
# tidelift: npm/comeback
# custom: ['https://your-domain.com/donate']
